# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rake'
gem 'guard'
gem 'guard-minitest'
gem 'rack-test'
gem 'minitest'
