version: '3.1'

services:
  web-base: &web-base
    build:
      context: ./web
    container_name: ringoro-web
    working_dir: /app
    volumes:
      - ./web:/app
    environment:
      - CARGO_TARGET_DIR=/app/target
    expose:
      - 8080
  test-base: &test-base
    build:
      context: ./test
    container_name: ringoro-integration-test
    working_dir: /work
    volumes:
      - ./test:/work
  web:
    <<: *web-base
    tty: true
    stdin_open: true
  apiserver:
    <<: *web-base
    command: cargo run
  apitest:
    <<: *test-base
    depends_on:
      - apiserver
    environment:
      WAIT_HOSTS: apiserver:8080
      WAIT_HOSTS_TIMEOUT: 60
      HOST: apiserver
      PORT: '8080'
    tty: true
    stdin_open: true
