version: '3.1'

services:
  redis:
    image: redis:6.2-rc1-alpine3.12
    expose:
      - 6379
    volumes:
      - ./docker/redis:/data
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - 27017
    volumes:
      - ./docker/db:/data/db
      - ./docker/configdb:/data/configdb
  web-base: &web-base
    build:
      context: ./docker/rust
      cache_from:
        - ringoro-rust-image-cache
    image: ringoro-rust-image:0.1.0
    working_dir: /app
    volumes:
      - ./rust:/app
      - ./rust/target/.registry:/usr/local/cargo/registry
      - ./rust/target/.cache:/usr/local/cargo/cache
    expose:
      - 80
  js-base: &js-base
    build:
      context: ./docker/js
    working_dir: /app
  web-unittest:
    <<: *web-base
    container_name: ringoro-ci-web-unittest
    environment: &rust-environment
      CARGO_TARGET_DIR: /app/target
      RINGORO_PORT: '80'
      RINGORO_DB_URI: 'mongodb://root:password@mongo:27017'
      RINGORO_DB_DATABASE: 'ringoro-dev'
      RINGORO_REDIS_ADDRESS: 'redis:6379'
      RINGORO_SESSION_KEY: '90ea9bde2a2c88a7614d7105a30257bc685da69799e7c400765a4331cac10cf0'
      RINGORO_TWITTER_CONSUMER_KEY: 'dummy'
      RINGORO_TWITTER_CONSUMER_SECRET: 'dummy'
      RINGORO_TWITTER_REDIRECT_URL: 'dummy'
      MONGO_TEST_URI: 'mongodb://root:password@mongo:27017'
      MONGO_TEST_DATABASE: 'ringoro-unittest'
      WAIT_HOSTS: mongo:27017, redis:6379
      WAIT_HOSTS_TIMEOUT: 60
    tty: true
    stdin_open: true
  apiserver:
    <<: *web-base
    container_name: ringoro-ci-apiserver
    environment:
      <<: *rust-environment
      RINGORO_HOST: 'apiserver'
      RINGORO_DB_DATABASE: 'ringoro-apitest'
    depends_on:
      - mongo
      - redis
    command: sh -c '/wait && cargo run'
  apitest:
    <<: *js-base
    container_name: ringoro-ci-api-test
    volumes:
      - ./js/api:/app
    environment:
      RINGORO_DB_URI: 'mongodb://root:password@mongo:27017'
      RINGORO_DB_DATABASE: 'ringoro-apitest'
      SERVER_ROOT_URL: 'http://apiserver'
      WAIT_HOSTS: apiserver:80
      WAIT_HOSTS_TIMEOUT: 60
    depends_on:
      - apiserver
    tty: true
    stdin_open: true
  frontend-unittest:
    <<: *js-base
    volumes:
      - ./js/frontend:/app
    container_name: ringoro-ci-frontend
