version: '3.1'

services:
  web:
    build:
      context: ./web
    container_name: ringoro-web
    working_dir: /app
    volumes:
      - ./web:/app
      - ./web/target/.registry:/usr/local/cargo/registry
      - ./web/target/.cache:/usr/local/cargo/cache
    environment:
      CARGO_TARGET_DIR: /app/target
    command: "cargo watch -x 'fmt -- --check' -x 'clippy --all-targets --all-features -- -D warnings' -x run"
    ports:
      - 8080:8080
    expose:
      - 8080
  test-base: &test-base
    build:
      context: ./test
    working_dir: /work
    volumes:
      - ./test:/work
    depends_on:
      - web
    tty: true
    stdin_open: true
  apitest:
    <<: *test-base
    container_name: ringoro-integration-test
    environment:
      HOST: web
      PORT: '8080'
