[package]
name = "ringoro-utils"
version = "0.1.0"
authors = ["tman <satominprpr@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bson = "1.1"
envy = "0.4"
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
