name: CI
on: push
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
jobs:
  backend-test:
    name: 'Server side test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and setup 
        run: |
          docker-compose -f docker-compose.ci.yml build --build-arg BUILDKIT_INLINE_CACHE=1 apiserver apitest
          docker-compose -f docker-compose.ci.yml run --rm -T apitest bundle install
      - name: Run fmt
        run: |
          docker-compose -f docker-compose.ci.yml run --rm web cargo fmt -- --check
      - name: Run clippy
        run: |
          docker-compose -f docker-compose.ci.yml run --rm web cargo clippy
      - name: Build
        run: |
          docker-compose -f docker-compose.ci.yml run --rm web cargo build
      - name: Run unit test
        run: |
          docker-compose -f docker-compose.ci.yml up -d web mongo web
          docker-compose -f docker-compose.ci.yml exec -T web /wait
          docker-compose -f docker-compose.ci.yml exec -T web cargo test --all -- --test-threads=1
          docker-compose -f docker-compose.ci.yml down
      - name: Run API test
        run: |
          docker-compose -f docker-compose.ci.yml up -d apiserver apitest
          docker-compose -f docker-compose.ci.yml exec -T apitest /wait
          docker-compose -f docker-compose.ci.yml exec -T apitest bundle exec rake api
          docker-compose -f docker-compose.ci.yml down
